
# run from repository root
# docker build -f Remote.Dockerfile -t cloud-agent:v0.1 .
# docker network create faas_nw
# docker-compose up

version: "3.7"

services:
  database:
      image: cloud-database:v0.1
      container_name: cloud-database
      hostname: cloud-database
      networks:
        faas_nw:
      ports: # 
        - "5000:5000" 
        - "5001:5001"
      volumes:
        - ./:/app:rw

  agent:
      image: cloud-agent:v0.1
      container_name: cloud-agent
      hostname: cloud-agent
      networks:
        faas_nw:
      environment: # deployed functions
        "PORT_START": "5000"
        "NUM_PORTS" : "5"
      ports: # 
        - "5000-5004:5000-5004" # deployed functions
        - "9000:9000"      # agent
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      volumes:
        - ./:/app:rw
      depends_on:
        - database

  proxy:
      image: cloud-proxy:v0.1
      container_name: cloud-proxy
      hostname: cloud-proxy
      networks:
        faas_nw:
      ports: # 
        - "9001:9001"
        - "9002:9002"
      # stdin_open: true # docker run -i
      # tty: true        # docker run -t
      volumes:
        - ./:/app:rw
      depends_on:
        - agent

  nats:
      image: nats
#      container_name: cloud-nats
#      hostname: cloud-nats
      ports:
        - "127.0.0.1:4222:4222"
        - "127.0.0.1:8222:8222"
      networks:
        faas_nw:
#      depends_on:
#        - proxy

  jaeger:
      container_name: cloud-jaeger
      hostname: cloud-jaeger
      image: jaegertracing/all-in-one:1.31
      networks:
        faas_nw:
      ports:
      - "16686:16686"
      - "14268:14268"
      deploy:
        resources:
          limits:
            cpus: '0.05'
            memory: 250M


networks:
  faas_nw:
    external:
      true