
# run from repository root
# docker build -f Remote.Dockerfile -t cloud-agent:v0.1 .
# docker network create faas_nw
# docker-compose up

version: "3.7"

services:
  database:
      image: rfa-database:v0.1
      container_name: rfa-database
      hostname: rfa-database
      networks:
        rfa-nw:
      ports: # 
        - "5000:5000" 
        - "5001:5001"
      deploy:
        resources:
          limits:
            cpus: '0.02'
            memory: 100M
      #volumes:
      #  - ./:/app:rw

  agent:
      image: rfa-agent:v0.1
      container_name: rfa-agent
      hostname: rfa-agent
      networks:
        rfa-nw:
      environment: # deployed functions
        "PORT_START": "6000"
        "NUM_PORTS" : "10"
        "DATABASE": "rfa-database:5000"
      ports: # 
        - "6000-6009:6000-6009" # deployed functions
        - "9000:9000"      # agent
      stdin_open: true # docker run -i
      tty: true        # docker run -t
#      volumes:
#        - ./:/app:rw
#      depends_on:
#        - database

  proxy:
      image: rfa-proxy:v0.1
      container_name: rfa-proxy
      hostname: rfa-proxy
      networks:
        rfa-nw:
      ports: #
        - "9999:9999"
        - "9998:9998"
#      # stdin_open: true # docker run -i
#      # tty: true        # docker run -t
##      volumes:
##        - ./:/app:rw
#      depends_on:
#        - agent

  nats:
      image: nats:alpine
      container_name: rfa-nats
      hostname: rfa-nats
      ports:
        - "127.0.0.1:4222:4222"
        - "127.0.0.1:8222:8222"
      networks:
        rfa-nw:

  jaeger:
      container_name: rfa-jaeger
      hostname: rfa-jaeger
      image: jaegertracing/all-in-one:1.31
      networks:
        rfa-nw:
      ports:
      - "16686:16686"
      - "14268:14268"
      deploy:
        resources:
          limits:
            cpus: '0.05'
            memory: 250M


networks:
  rfa-nw:
    external:
      true