
# run from repository root
# docker build -f Remote.Dockerfile -t cloud-agent:v0.1 .
# docker network create faas_nw
# docker-compose up

version: "3.7"

services:

  jaeger:
      container_name: jaeger
      hostname: jaeger
      image: jaegertracing/all-in-one:1.31
      networks:
        faas_nw:
      ports:
      - "16686:16686"
      - "14268:14268"
      deploy:
        resources:
          limits:
            cpus: '0.05'
            memory: 250M

  rms:
    image: cloud-agent:v0.1
    networks:
      faas_nw:
    environment: # deployed functions
      "PORT_START": "5000"
      "NUM_PORTS" : "5"
    ports: # 
      - "5000-5004:5000-5004" # deployed functions
      - "9000:9000"      # agent
    container_name: cloud-agent
    hostname: agent-faas
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./:/app:rw
    
  redis:
      image: "redis:alpine3.13"
      ports:
        - "6379:6379"
      container_name: redis
      hostname: redis  
      networks:
        faas_nw:

networks:
  faas_nw:
    external:
      true