version: '3'


vars:
    DOCKER_REMOTE: ishan27g/ryo-faas
    IMAGE_AGENT: rfa-agent.v0.1
    IMAGE_PROXY: rfa-proxy.v0.1
    IMAGE_DATABASE: rfa-database.v0.1
    IMAGE_DEPLOY_BASE: rfa-deploy-base.v0.1

tasks:

  # cleanup test dirs/
  testCleanup:
    cmds:
      - rm -rf ./agent/registry/deploy/
      - rm -rf ./database/handler/ok*
      # - c
  test:
    cmds:
      # - defer: { task: testCleanup }
      - go test --v ./...
  test-ci:
    cmds:
      - go test --v ./...
  nats:
    cmds:
      - docker compose run --service-ports --rm nats
  jaeger:
    cmds:
      - docker compose run --service-ports --rm jaeger
  zipkin:
    cmds:
      - docker compose run --service-ports --rm zipkin

  # run database
  database:
    dir: database
    cmds:
      - go run main.go

  # run proxy
  proxy:
    dir: proxy
    cmds:
      - go run main.go -agents :9000
  
  # run agent
  agent:
    dir: agent
    cmds:
      - go run main.go

  # run database events example
  examples-db:
     dir: examples/database-events
     cmds:
      - go run main.go subscribe.go
  
  # test database events example 
  examples-db-test:
    cmds:
      - curl http://localhost:9999/pay
      - sleep 2 && echo 'getting'
      - curl http://localhost:9999/get

  # call via go to run in parallel
  imgProxy:
    cmds:
      - docker build -f proxy.dockerfile -t {{.DOCKER_REMOTE}}:{{.IMAGE_PROXY}} .
  imgDb:
    cmds:
      - docker build -f db.dockerfile -t {{.DOCKER_REMOTE}}:{{.IMAGE_DATABASE}} .
  imgDeployBase:
    cmds:
      - docker build -f deploy-base.dockerfile -t {{.DOCKER_REMOTE}}:{{.IMAGE_DEPLOY_BASE}} .

  pushImages:
      cmds:
        - docker push {{.DOCKER_REMOTE}}:{{.IMAGE_PROXY}}
        - docker push {{.DOCKER_REMOTE}}:{{.IMAGE_DATABASE}}
        - docker push {{.DOCKER_REMOTE}}:{{.IMAGE_DEPLOY_BASE}}

  metaGolangTask:
      cmds:
        - go run taskFile.go -buildImages
        - go run taskFile.go -pushImages

