name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Start Nats
      uses: onichandame/nats-action@master
      with:
        port: "4222"

    - name: test connection to nats
      uses: onichandame/nats-client-action@master
      with:
        servers: "nats://localhost:4222"

    - name: Install Task
      uses: arduino/setup-task@v1
    
    - name: Test
      run: task test-ci
    
